services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes: [ .:/usr/src/app:Z ]
    ports: [ 4040:4040 ]
    user: 1000:1000
    environment: [ JEKYLL_ENV=docker ]
    command: jekyll serve -H 0.0.0.0 -P 4040 -w --config _config.yml,_config_docker.yml
